server:
  port: ${PORT:8081}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.jdbc.core: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  # Redis config (commented)
  # redis:
  #   host: redis-17015.c305.ap-south-1-1.ec2.redns.redis-cloud.com
  #   port: 17015
  #   username: default
  #   password: aVEwAkB7P378hrsvsfHIjP9KK8yVMOKB

  data:
    redis:
      repositories:
        enabled: false

  datasource:
    url: jdbc:mysql://yamanote.proxy.rlwy.net:27466/railway
    username: root
    password: amPKXoXZmmKZYqZyOEATVPnyrjHoUTwy
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: shubhamchikane41216@gmail.com
    password: dzdqfposudfvalcc
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
    debug: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB  

application:
  name: journalApp

cloudinary:
  cloud-name: dlttny8or 
  api-key: 316495775999264 
  api-secret: ewojKrowJkViOhz2z_LHDUHzJdE 

weather_key: 7d7664073fb43abe8381fea1ff1b7a0e