server:
  port: 8088

# Uncomment and update if you want to set a specific context path
# servlet:
#   context-path: /v1

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.jdbc.core: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#spring:  # Redis database for local
#  redis:
#    host: localhost
#    port: 6379

spring:
  redis:
    host: redis-17015.c305.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 17015
    username: default
    password: ${REDIS_PASS}

  application:
    name: journalApp

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: shubhamchikane41216@gmail.com
    password: ${GMAIL_OTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
  starttls.enable: true

 # File Upload Configuration
servlet:
  multipart:
   max-file-size: 100MB
   max-request-size: 100MB  

# Uncomment the following section if needed
# jpa:
#   show-sql: true
#   properties:
#     hibernate:
#       dialect: org.hibernate.dialect.MySQLDialect
#       id.new_generator_mappings: false
#       format_sql: true  

cloudinary:
  cloud-name: ${CLOUD_NAME} 
  api-key: ${API_KEY} 
  api-secret: ${API_SECRET} 

weather_key: ${WEATHER_KEY}