server:
  port: 8090
  servlet:
    context-path: /v1

spring:
  application:
    name: journalApp

  datasource:
    url: jdbc:mysql://127.0.0.1:3308/journal_php_db
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        jdbc:
          core: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
